# Auto-generated by Report Studio. Do not edit by hand.
# This file is the on-disk runner for a published Studio report. The Studio
# config (columns, filters, joins, calculations) lives on the linked
# `Report Studio Report` doc and is shipped via the `fixtures` hook. This
# file just delegates to the report_builder engine so a teammate who pulls
# the app gets a working report after `bench migrate`.
from report_builder.api.builder import run_for_standard_report

STUDIO_REPORT = 'RPT-00065'


def execute(filters=None):
	result = run_for_standard_report(STUDIO_REPORT, filters)
	columns = result["columns"]
	rows = result["rows"]
	return columns, rows
